// Static data loader for the GIPRE Transparency platform.
// Imports the 9 JSON files generated by `scripts/build_site_data.py`.
// Next.js bundles these at build time — zero runtime fetch cost.

import agentsJson from "../../data/agents.json";
import buildStateJson from "../../data/build_state.json";
import changelogJson from "../../data/changelog.json";
import governanceJson from "../../data/governance.json";
import layersJson from "../../data/layers.json";
import methodologyJson from "../../data/methodology.json";
import outputsJson from "../../data/outputs.json";
import planJson from "../../data/plan.json";
import scenariosJson from "../../data/scenarios.json";

// ─────────────────────────────────────────────────────────────────────────────
// Types — kept lightweight; the JSON shape is the source of truth.
// ─────────────────────────────────────────────────────────────────────────────

export type StepStatus = "done" | "in_progress" | "pending" | "blocked" | "planned" | "unknown";

export interface PlanStep {
  id: string;
  title: string;
  status_cell: string;
  status: StepStatus;
}

export interface PlanPhase {
  id: string;
  title: string;
  n_steps: number;
  n_done: number;
  n_in_progress: number;
  n_pending: number;
  steps: PlanStep[];
}

export interface PlanData {
  phases: PlanPhase[];
  [k: string]: unknown;
}

export interface BuildStateData {
  version: string;
  phases_total: number;
  steps_total: number;
  steps_done: number;
  steps_in_progress: number;
  steps_pending: number;
  agents_total: number;
  layers_total: number;
  layers_active: number;
  scenarios_total: number;
  generated_utc: string;
  [k: string]: unknown;
}

export interface Agent {
  id: string;
  role: string;
  label: string;
  iso3?: string;
  tier?: string;
  backbone?: string;
  spec?: string;
  [k: string]: unknown;
}

export interface AgentsData {
  agents: Agent[];
  [k: string]: unknown;
}

export interface Layer {
  id: string;
  title: string;
  status: string;
  [k: string]: unknown;
}

export interface LayersData {
  layers: Layer[];
  [k: string]: unknown;
}

export interface GovernanceData {
  [k: string]: unknown;
}

export interface MethodologyData {
  [k: string]: unknown;
}

export interface ScenariosData {
  [k: string]: unknown;
}

export interface ChangelogData {
  [k: string]: unknown;
}

export interface OutputsData {
  [k: string]: unknown;
}

// ─────────────────────────────────────────────────────────────────────────────
// Exports
// ─────────────────────────────────────────────────────────────────────────────

export const planData = planJson as unknown as PlanData;
export const buildStateData = buildStateJson as unknown as BuildStateData;
export const agentsData = agentsJson as unknown as AgentsData;
export const layersData = layersJson as unknown as LayersData;
export const governanceData = governanceJson as unknown as GovernanceData;
export const methodologyData = methodologyJson as unknown as MethodologyData;
export const scenariosData = scenariosJson as unknown as ScenariosData;
export const changelogData = changelogJson as unknown as ChangelogData;
export const outputsData = outputsJson as unknown as OutputsData;
