// Static data loader for the GIPRE Transparency platform.
// Imports the 9 JSON files generated by `scripts/build_site_data.py`.
// Next.js bundles these at build time — zero runtime fetch cost.

import agentsJson from "../../data/agents.json";
import buildStateJson from "../../data/build_state.json";
import changelogJson from "../../data/changelog.json";
import governanceJson from "../../data/governance.json";
import layersJson from "../../data/layers.json";
import methodologyJson from "../../data/methodology.json";
import outputsJson from "../../data/outputs.json";
import planJson from "../../data/plan.json";
import scenariosJson from "../../data/scenarios.json";

// ─────────────────────────────────────────────────────────────────────────────
// Plan / phase types
// ─────────────────────────────────────────────────────────────────────────────

export type StepStatus = "done" | "in_progress" | "pending" | "blocked" | "planned" | "unknown";

export interface PlanStep {
  id: string;
  title: string;
  status_cell: string;
  status: StepStatus;
}

export interface PlanPhase {
  id: string;
  title: string;
  n_steps: number;
  n_done: number;
  n_in_progress: number;
  n_pending: number;
  steps: PlanStep[];
}

export interface PlanData {
  phases: PlanPhase[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Build state
// ─────────────────────────────────────────────────────────────────────────────

export interface BuildStateData {
  version: string;
  phases_total: number;
  steps_total: number;
  steps_done: number;
  steps_in_progress: number;
  steps_pending: number;
  completion_pct: number;
  layers_total: number;
  layers_active: number;
  agents_total: number;
  agents_target: number;
  pdf_cycles: number;
  generated_utc: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Agents
// ─────────────────────────────────────────────────────────────────────────────

export interface Agent {
  id: string;
  role: string;
  label: string;
  iso3?: string;
  tier?: string;
  backbone?: string;
  spec?: string;
  [k: string]: unknown;
}

export interface AgentsData {
  agents: Agent[];
  by_class: Record<string, number>;
  by_backbone: Record<string, number>;
  n_total: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Layers
// ─────────────────────────────────────────────────────────────────────────────

export interface Layer {
  id: string;
  cluster: string;
  name: string;
  status: string;
  summary?: string;
  [k: string]: unknown;
}

export interface LayerCluster {
  id: string;
  title: string;
  layer_range: string;
  n_layers_total: number;
  n_active: number;
  layers: Layer[];
}

export interface LayersData {
  layers: Layer[];
  by_cluster: Record<string, LayerCluster>;
  n_total: number;
  n_active: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Governance (N01 / N02 audit runs)
// ─────────────────────────────────────────────────────────────────────────────

export interface GovernanceRunSummary {
  id: string;
  target_class: string;
  gate: string;
  score_mean: number;
  score_stddev: number;
  n_findings: number;
  n_critical: number;
}

export interface GovernanceRun {
  step: string;
  run_id: string;
  synthesis_md: string;
  synthesis_md_full_length: number;
  n_artifacts: number;
  summaries: GovernanceRunSummary[];
  available: boolean;
  structural_metrics_csv_exists?: boolean;
}

export interface GovernanceData {
  n01: GovernanceRun;
  n02: GovernanceRun;
}

// ─────────────────────────────────────────────────────────────────────────────
// Methodology
// ─────────────────────────────────────────────────────────────────────────────

export interface MethodologyData {
  digest_excerpt: string;
  digest_full_length: number;
  source_files: string[];
  architecture_md?: string;
  readme_md?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Scenarios + Changelog + Outputs (loose; rarely accessed)
// ─────────────────────────────────────────────────────────────────────────────

export interface ScenarioKey {
  stress_level: number;
  gp_archetype: string;
  flashpoints: string[];
}

export interface Scenario {
  id: string;
  key: ScenarioKey;
  title: string;
  short_narrative: string;
  medium_narrative: string;
  long_narrative: string;
  probability: number;
  ci_low: number;
  ci_high: number;
  qre_payoff_table: Record<string, unknown>;
  triggers: string[];
  country_impacts: Record<string, unknown>;
  theme_impacts: Record<string, unknown>;
  historical_analogues: string[];
  horizon_priority: string[];
}

export interface ScenariosData {
  scenarios: Scenario[];
  n_total: number;
  source_file?: string;
}

export interface ChangelogEntry {
  version: string;
  title: string;
  body: string;
  body_full_length?: number;
  body_excerpt?: string;
}

export interface ChangelogData {
  entries: ChangelogEntry[];
  n_entries: number;
}

export interface OutputsData {
  [k: string]: unknown;
}

// ─────────────────────────────────────────────────────────────────────────────
// Exports — JSON cast to the specific interfaces
// ─────────────────────────────────────────────────────────────────────────────

export const planData = planJson as unknown as PlanData;
export const buildStateData = buildStateJson as unknown as BuildStateData;
export const agentsData = agentsJson as unknown as AgentsData;
export const layersData = layersJson as unknown as LayersData;
export const governanceData = governanceJson as unknown as GovernanceData;
export const methodologyData = methodologyJson as unknown as MethodologyData;
export const scenariosData = scenariosJson as unknown as ScenariosData;
export const changelogData = changelogJson as unknown as ChangelogData;
export const outputsData = outputsJson as unknown as OutputsData;
